name: GitHub Actions Failure Practice

"on":
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: First Job Start
        run: echo "First job started"

      - name: Intentional Failure
        run: |
          echo "This step will fail intentionally"
          exit 1

      - name: This Will Be Skipped
        run: echo "You should not see this message"

  second-job:
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Second Job
        run: echo "Second job should be skipped"