name: First GitHub Actions Workflow

"on":
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: First Job Start
        run: |
          echo "First Job started"
          date

      - name: First Job Wait
        run: |
          echo "First Job is running..."
          sleep 10
          echo "First Job finished"
          date

  second-job:
    needs: first-job
    runs-on: ubuntu-latest

    steps:
      - name: Second Job Start
        run: |
          echo "Second Job started"
          date

      - name: Second Job Message
        run: echo "Second Job started after First Job completed"