name: First GitHub Actions Workflow

"on":
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: First Job
        run: |
          echo "First job completed"

  second-job:
    runs-on: ubuntu-latest

    steps:
      - name: Second Job
        run: |
          echo "Second job completed"

  third-job:
    needs: [first-job, second-job]
    runs-on: ubuntu-latest

    steps:
      - name: Third Job
        run: |
          echo "Third job starts only after first and second jobs finish"